---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart employee application
  ansible.builtin.systemd:
    name: "{{ employee_app_service_name }}"
    state: restarted
