---
apiVersion: v1
kind: Namespace

metadata:
  name: employee-directory

  labels:
    app.kubernetes.io/name: employee-directory
    app.kubernetes.io/part-of: homelab-platform
    app.kubernetes.io/managed-by: kubectl
