[kubernetes_control_plane]
k8s-lab ansible_host=192.168.56.20

[kubernetes_workers]

[kubernetes_cluster:children]
kubernetes_control_plane
kubernetes_workers

[kubernetes_cluster:vars]
ansible_user=base