---
flannel_manifest_url: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

flannel_manifest_path: /etc/kubernetes/manifests/kube-flannel.yml

flannel_namespace: kube-flannel

kubernetes_admin_config: /etc/kubernetes/admin.conf
